theme: minima
title: Blogspot
author: Rohit Raj
email: rj.148055@gmail.com
description: Welcome, now lets discuss about some good project ideas for cloud using Azure cloud
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
